<?php

/**
 * @file
 * Contains as_menu_plug.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Generates markup around link title on the page().
 */
function as_menu_plug_generate_link_markup($link_title) {
  $markup = NULL;
    // get variables from array being passed to this function
    //dump($section_label_data);
    $link_name = preg_replace('/\W+/','-',strtolower(strip_tags($link_title)));;
    // Create the markup
    $markup = $markup . "<li><a href='#" . $link_name . "'>" . $link_title . "</a></li>";

    return $markup;
  }


/**
* Strips menu URI string anc converts to menu_link_id or nid.
*/
function as_menu_plug_strip_id($string) {

    if (!empty($string)) {
      $string = strstr($string, '/');
      $string = str_replace('/', '', $string);
      return $string;
    }
  }

/**
* Turns menu link id into parent node id.
*/
function as_menu_plug_menulinkid_nid($menu_link_id) {

    $database =  \Drupal::database();
    $sql = "SELECT link__uri FROM menu_link_content_data WHERE id = :menulinkid";
    $query = $database->query($sql, [':menulinkid' => $menu_link_id]);
    $result = $query->fetchObject();
    if ($result !== false) {
      //$node = Node::load($result->nid);
      return $result->link__uri;
    }

  }


/**
* Implements hook_preprocess_HOOK() for menu.html.twig.
*/
function as_menu_plug_preprocess_menu(&$variables) {
  // If there is not an existing class array, create an empty array.
  if (!isset($variables['attributes']['class'])) {
    $variables['attributes']['class'] = [];
  }
  // Merge with any classes that may have been set by other hook_preprocess_menu invocations
  $variables['attributes']['class'] = array_merge($variables['attributes']['class'], ['doortyweefooker']);
}

/**
 * Implements hook_help().
 */
function as_menu_plug_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_menu_plug module.
    case 'help.page.as_menu_plug':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configurations, fucntions and templates to add in-page anchor links as link fields under that page&#039;&#039;s menu item.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function as_menu_plug_theme() {
  return [
    'default_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
