<?php

/**
 * @file
 * Contains as_menu_plug.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Generates markup around link title on the page().
 */
function as_menu_plug_generate_link_markup($link_title) {
  $markup = NULL;
    // get variables from array being passed to this function
    //dump($section_label_data);
    $link_name = preg_replace('/\W+/','-',strtolower(strip_tags($link_title)));;
    // Create the markup
    $markup = $markup . "<li><a href='#" . $link_name . "'>" . $link_title . "</a></li>";

    return $markup;
  }

/**
 * Generates links for card view().
 */
function as_menu_plug_generate_card_link_markup($link_title,$page_value) {
  $markup = NULL;
    // get variables from array being passed to this function
    //dump($section_label_data);
    $link_name = preg_replace('/\W+/','-',strtolower(strip_tags($link_title)));;
    // Create the markup
    $markup = $markup . "<li><a href='". $page_value . "#" . $link_name . "'>" . $link_title . "</a></li>";

    return $markup;
  }

/**
 * Generates link for menu entry().
 */
function as_menu_plug_generate_menu_link($link_title,$page_value) {

    // get variables from array being passed to this function
    //dump($section_label_data);
    //clean up text
    $link_uri = preg_replace('/\W+/','-',strtolower(strip_tags($link_title)));;
    //build path
    $link_uri = $page_value . "#" . $link_uri;
    // populate the array
    $link = array();
    $link["uri"] = $link_uri;
    $link["title"] = $link_title;
    $link["page_value"] = $page_value;

    return $link;
  }


/**
* Implements hook_preprocess_HOOK() for menu.html.twig.
*/
function as_menu_plug_preprocess_menu(&$variables) {
  // If there is not an existing class array, create an empty array.
  if (!isset($variables['attributes']['class'])) {
    $variables['attributes']['class'] = [];
  }
  // Merge with any classes that may have been set by other hook_preprocess_menu invocations
  $variables['attributes']['class'] = array_merge($variables['attributes']['class'], ['doortyweefooker']);
}

/**
 * Implements hook_help().
 */
function as_menu_plug_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_menu_plug module.
    case 'help.page.as_menu_plug':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configurations, fucntions and templates to add in-page anchor links as link fields under that page&#039;&#039;s menu item.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function as_menu_plug_theme() {
  return [
    'default_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
