<?php

/**
 * @file
 * Contains as_menu_spackle.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_menu_spackle_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_menu_spackle module.
    case 'help.page.as_menu_spackle':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides am ordered list of in-page menu items as a field associated with a given page&#039;&#039;s menu items') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function as_menu_spackle_theme() {
  return [
    'as_menu_spackle' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function as_menu_spackle_theme() {
  return [
    'new_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
