https://{default}/:
  type: upstream
  upstream: drupal8:http
  primary: null
  id: null
  attributes: {}
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
https://departments.asd8.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
https://anthro.asd8.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
https://history.asd8.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
https://people.asd8.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
https://asd7.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept1.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept2.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept3.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept4.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept5.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept6.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept7.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept8.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept9.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://dept10.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://cder.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://baroqueorgan.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.baroqueorgan.cornell.edu/:
    type: redirect
    to: https://baroqueorgan.cornell.edu/
https://cogsci.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.cogsci.cornell.edu/:
    type: redirect
    to: https://cogsci.cornell.edu/
https://frenchstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.frenchstudies.cornell.edu/:
    type: redirect
    to: https://frenchstudies.cornell.edu/
https://igcs.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.igcs.cornell.edu/:
    type: redirect
    to: https://igcs.cornell.edu/
https://mediastudies.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.mediastudies.as.cornell.edu/:
    type: redirect
    to: https://mediastudies.as.cornell.edu/
https://medievalstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.medievalstudies.cornell.edu/:
    type: redirect
    to: https://medievalstudies.cornell.edu/
https://rural.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://sct.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.sct.cornell.edu/:
    type: redirect
    to: https://sct.cornell.edu/
https://icm.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://inequality.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.inequality.cornell.edu/:
    type: redirect
    to: https://inequality.cornell.edu/
https://africana.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.africana.cornell.edu/:
    type: redirect
    to: https://africana.cornell.edu/
https://asrc.cornell.edu/:
    type: redirect
    to: https://africana.cornell.edu/
https://www.asrc.cornell.edu/:
    type: redirect
    to: https://africana.cornell.edu/
https://americanstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://anthropology.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.anthropology.cornell.edu/:
    type: redirect
    to: https://anthropology.cornell.edu/
https://archaeology.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.archaeology.cornell.edu/:
    type: redirect
    to: https://archaeology.cornell.edu/
https://ciams.cornell.edu/:
    type: redirect
    to: https://archaeology.cornell.edu/
https://www.ciams.cornell.edu/:
    type: redirect
    to: https://archaeology.cornell.edu/
https://asianamericanstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.asianamericanstudies.cornell.edu/:
    type: redirect
    to: https://asianamericanstudies.cornell.edu.edu/
https://asianstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.asianstudies.cornell.edu/:
    type: redirect
    to: https://asianstudies.cornell.edu/
https://caps.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.caps.cornell.edu/:
    type: redirect
    to: https://caps.cornell.edu/
https://classics.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.classics.cornell.edu/:
    type: redirect
    to: https://classics.cornell.edu/
https://complit.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.complit.cornell.edu/:
    type: redirect
    to: https://complit.cornell.edu/
https://complit.arts.cornell.edu/:
    type: redirect
    to: https://complit.cornell.edu/
https://www.complit.arts.cornell.edu/:
    type: redirect
    to: https://complit.cornell.edu/
https://sts.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.sts.cornell.edu/:
    type: redirect
    to: https://sts.cornell.edu/
https://cinema.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.cinema.cornell.edu/:
    type: redirect
    to: https://cinema.cornell.edu/
https://ecologyandevolution.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.ecologyandevolution.cornell.edu/:
    type: redirect
    to: https://ecologyandevolution.cornell.edu/
https://economics.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.economics.cornell.edu/:
    type: redirect
    to: https://economics.cornell.edu/
https://fgss.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.fgss.cornell.edu/:
    type: redirect
    to: https://fgss.cornell.edu/
https://german.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.german.cornell.edu/:
    type: redirect
    to: https://german.cornell.edu/
https://government.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.government.cornell.edu/:
    type: redirect
    to: https://government.cornell.edu/
https://government.arts.cornell.edu/:
    type: redirect
    to: https://government.cornell.edu/
https://www.government.arts.cornell.edu/:
    type: redirect
    to: https://government.cornell.edu/
https://history.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.history.cornell.edu/:
    type: redirect
    to: https://history.cornell.edu/
https://history.arts.cornell.edu/:
    type: redirect
    to: https://history.cornell.edu/
https://www.history.arts.cornell.edu/:
    type: redirect
    to: https://history.cornell.edu/
https://arthistory.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.arthistory.cornell.edu/:
    type: redirect
    to: https://arthistory.cornell.edu/
https://jewishstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.jewishstudies.cornell.edu/:
    type: redirect
    to: https://jewishstudies.cornell.edu/
https://knight.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.knight.as.cornell.edu/:
    type: redirect
    to: https://knight.as.cornell.edu/
https://lrc.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.lrc.cornell.edu/:
    type: redirect
    to: https://lrc.cornell.edu/
https://wld.lrc.cornell.edu/:
    type: redirect
    to: https://lrc.cornell.edu/
https://latino.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.latino.cornell.edu/:
    type: redirect
    to: https://latino.cornell.edu/
https://lgbt.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.lgbt.cornell.edu/:
    type: redirect
    to: https://lgbt.cornell.edu/
https://linguistics.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.linguistics.cornell.edu/:
    type: redirect
    to: https://linguistics.cornell.edu/
https://knight.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.knight.as.cornell.edu/:
    type: redirect
    to: https://knight.as.cornell.edu/
