https://first.{default}/:
  type: upstream
  upstream: app:http
https://departments.asd8.as.cornell.edu/:
  type: upstream
  upstream: app:http
https://people.asd8.as.cornell.edu/:
  type: upstream
  upstream: app:http
http://asd8.as.cornell.edu/:
  primary: null
  id: null
  attributes: {}
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: app:http
