https://as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
https://www.as.cornell.edu/:
  type: redirect
  to: https://as.cornell.edu/
https://arts.cornell.edu/:
  type: redirect
  to: https://as.cornell.edu/
https://www.arts.cornell.edu/:
  type: redirect
  to: https://as.cornell.edu/
https://asd8.as.cornell.edu/:
  type: redirect
  to: https://as.cornell.edu/
https://people.asd8.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
https://people.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://cder.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://baroqueorgan.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://cogsci.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.cogsci.cornell.edu/:
  type: redirect
  to: https://cogsci.cornell.edu/
https://frenchstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://igcs.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://mediastudies.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://medievalstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.medievalstudies.cornell.edu/:
  type: redirect
  to: https://medievalstudies.cornell.edu/
https://rural.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://sct.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.sct.cornell.edu/:
  type: redirect
  to: https://sct.cornell.edu/
https://icm.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://inequality.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.inequality.cornell.edu/:
  type: redirect
  to: https://inequality.cornell.edu/
https://africana.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.africana.cornell.edu/:
  type: redirect
  to: https://africana.cornell.edu/
https://asrc.cornell.edu/:
  type: redirect
  to: https://africana.cornell.edu/
https://www.asrc.cornell.edu/:
  type: redirect
  to: https://africana.cornell.edu/
https://americanstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://anthropology.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.anthropology.cornell.edu/:
  type: redirect
  to: https://anthropology.cornell.edu/
https://archaeology.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.archaeology.cornell.edu/:
  type: redirect
  to: https://archaeology.cornell.edu/
https://ciams.cornell.edu/:
  type: redirect
  to: https://archaeology.cornell.edu/
https://www.ciams.cornell.edu/:
  type: redirect
  to: https://archaeology.cornell.edu/
https://asianamericanstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.asianamericanstudies.cornell.edu/:
  type: redirect
  to: https://asianamericanstudies.cornell.edu.edu/
https://asianstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.asianstudies.cornell.edu/:
  type: redirect
  to: https://asianstudies.cornell.edu/
https://caps.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.caps.cornell.edu/:
  type: redirect
  to: https://caps.cornell.edu/
https://classics.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.classics.cornell.edu/:
  type: redirect
  to: https://classics.cornell.edu/
https://complit.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.complit.cornell.edu/:
  type: redirect
  to: https://complit.cornell.edu/
https://complit.arts.cornell.edu/:
  type: redirect
  to: https://complit.cornell.edu/
https://www.complit.arts.cornell.edu/:
  type: redirect
  to: https://complit.cornell.edu/
https://sts.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.sts.cornell.edu/:
  type: redirect
  to: https://sts.cornell.edu/
https://cinema.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.cinema.cornell.edu/:
  type: redirect
  to: https://cinema.cornell.edu/
https://ecologyandevolution.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.ecologyandevolution.cornell.edu/:
  type: redirect
  to: https://ecologyandevolution.cornell.edu/
https://economics.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.economics.cornell.edu/:
  type: redirect
  to: https://economics.cornell.edu/
https://fgss.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://german.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://government.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.government.cornell.edu/:
  type: redirect
  to: https://government.cornell.edu/
https://government.arts.cornell.edu/:
  type: redirect
  to: https://government.cornell.edu/
https://www.government.arts.cornell.edu/:
  type: redirect
  to: https://government.cornell.edu/
https://history.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.history.cornell.edu/:
  type: redirect
  to: https://history.cornell.edu/
https://history.arts.cornell.edu/:
  type: redirect
  to: https://history.cornell.edu/
https://www.history.arts.cornell.edu/:
  type: redirect
  to: https://history.cornell.edu/
https://arthistory.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.arthistory.cornell.edu/:
  type: redirect
  to: https://arthistory.cornell.edu/
https://jewishstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.jewishstudies.cornell.edu/:
  type: redirect
  to: https://jewishstudies.cornell.edu/
https://knight.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.knight.as.cornell.edu/:
  type: redirect
  to: https://knight.as.cornell.edu/
https://lrc.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.lrc.cornell.edu/:
  type: redirect
  to: https://lrc.cornell.edu/
https://latino.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.latino.cornell.edu/:
  type: redirect
  to: https://latino.cornell.edu/
https://lgbt.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://linguistics.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.linguistics.cornell.edu/:
  type: redirect
  to: https://linguistics.cornell.edu/
https://romancestudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.romancestudies.cornell.edu/:
  type: redirect
  to: https://romancestudies.cornell.edu/
https://milstein-program.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.milstein-program.as.cornell.edu/:
  type: redirect
  to: https://milstein-program.as.cornell.edu/
https://music.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.music.cornell.edu/:
  type: redirect
  to: https://music.cornell.edu/
https://neareasternstudies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.neareasternstudies.cornell.edu/:
  type: redirect
  to: https://neareasternstudies.cornell.edu/
https://societyhumanities.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.societyhumanities.as.cornell.edu/:
  type: redirect
  to: https://societyhumanities.as.cornell.edu/
https://pma.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.pma.cornell.edu/:
  type: redirect
  to: https://pma.cornell.edu/
https://philosophy.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.philosophy.cornell.edu/:
  type: redirect
  to: https://philosophy.cornell.edu/
https://psychology.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.psych.cornell.edu/:
  type: redirect
  to: https://psychology.cornell.edu/
https://religious-studies.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.religious-studies.cornell.edu/:
  type: redirect
  to: https://religious-studies.cornell.edu/
https://sociology.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.soc.cornell.edu/:
  type: redirect
  to: https://sociology.cornell.edu/
https://chemistry.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.chemistry.cornell.edu/:
  type: redirect
  to: https://chemistry.cornell.edu/
https://chem.cornell.edu/:
  type: redirect
  to: https://chemistry.cornell.edu/
https://www.chem.cornell.edu/:
  type: redirect
  to: https://chemistry.cornell.edu/
https://safety.chem.cornell.edu/:
  type: redirect
  to: https://chemistry.cornell.edu/safety
https://physics.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.physics.cornell.edu/:
  type: redirect
  to: https://physics.cornell.edu/
https://nbb.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.nbb.cornell.edu/:
  type: redirect
  to: https://nbb.cornell.edu/
https://english.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.english.cornell.edu/:
  type: redirect
  to: https://english.cornell.edu/
https://english.arts.cornell.edu/:
  type: redirect
  to: https://english.cornell.edu/
https://www.english.arts.cornell.edu/:
  type: redirect
  to: https://english.cornell.edu/
https://epoch.cornell.edu/:
  type: redirect
  to: https://english.cornell.edu/
https://www.epoch.cornell.edu/:
  type: redirect
  to: https://english.cornell.edu/epoch-magazine-0
https://writers.cornell.edu/:
  type: redirect
  to: https://english.cornell.edu/writersatcornell
https://research.astro.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.research.astro.cornell.edu/:
  type: redirect
  to: https://english.cornell.edu/
https://carlsaganinstitute.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://communications.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://astro.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.astro.cornell.edu/:
  type: redirect
  to: https://astro.cornell.edu/
https://math.cornell.edu/:
  type: upstream
  upstream: drupal7:http
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
https://www.math.cornell.edu/:
  type: redirect
  to: https://math.cornell.edu/
