https://{default}/:
  type: upstream
  upstream: drupal8:http
  primary: null
  id: null
  attributes: {}
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/', 'SimpleSAMLSessionID', 'SimpleSAMLAuthToken']
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
https://departments.asd8.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
https://anthro.asd8.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
https://history.asd8.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
https://people.asd8.as.cornell.edu/:
  type: upstream
  upstream: drupal8:http
https://asd7.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
https://dept1.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
https://dept2.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
https://dept3.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
https://dept4.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
https://dept5.as.cornell.edu/:
  type: upstream
  upstream: drupal7:http
