<?php

/**
 * @file
 * Contains as_manage_vocabularies.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_manage_vocabularies_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_stats module.
    case 'help.page.as_manage_vocabularies':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds menu entries to the edit content tab and an admin view with basic tasks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Remove 'path.temporary' config if redundant.
 */
function as_manage_vocabularies_system_update_8801() {
  // If settings is already being used, or the config is set to the OS default,
  // clear the config value.
  $config = Drupal::configFactory()->getEditable('system.file');
  if (Settings::get('file_temp_path') || $config->get('path.temporary') === FileSystem::getOsTemporaryDirectory()) {
    $config->clear('path.temporary')
      ->save(TRUE);
  }
}
